# API 0.1.0

In [1]:
import predicode as pc
import tensorflow.keras as keras

In [2]:
hpc = pc.Hierarchical()

In [3]:
hpc.add_tier(shape=(10, ))

In [4]:
hpc.add_tier(shape=(4, ))

Active connection: tier_1 -> tier_0


In [5]:
hpc.summary()

# Tier 1: tier_1

# Connection: tier_1 -> tier_0
(No tier connection defined.)

# Tier 0: tier_0


In [6]:
hpc.connection = pc.connections.TopDownSequential()

In [7]:
hpc.connection.add(keras.layers.Dense(10, input_shape=(4, )))

In [8]:
hpc.summary()

# Tier 1: tier_1

# Connection: tier_1 -> tier_0
Top-down prediction.
## Predictive model
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
Total params: 50
Trainable params: 50
Non-trainable params: 0
_________________________________________________________________
## Prediction error
## Loss function
<function mean_squared_error at 0x7f52f3500290>

# Tier 0: tier_0


In [9]:
dataset = pc.datasets.decaying_multi_normal(10, 100)

In [10]:
hpc.compile(optimizer='adam', metrics=[keras.metrics.MeanSquaredError()])

In [11]:
dataset.dtype

dtype('float32')

In [12]:
hpc.connection.predictor_variables

[<tf.Variable 'dense/kernel:0' shape=(4, 10) dtype=float32, numpy=
 array([[-0.20538154, -0.08118117,  0.24260747,  0.33645934,  0.45365012,
          0.34589803,  0.61022305, -0.02507949,  0.3167523 ,  0.2971964 ],
        [ 0.5967524 , -0.38332626,  0.41547942, -0.35833043,  0.07957852,
         -0.31373525,  0.20931184, -0.38950115, -0.53360397, -0.37396604],
        [ 0.14686686,  0.6494504 ,  0.22843075,  0.6392746 , -0.02602363,
          0.21333808, -0.43419605, -0.02862209,  0.09796304,  0.41193616],
        [ 0.56853485,  0.55402255,  0.03882158,  0.18191606,  0.09943056,
          0.19884247,  0.15815717,  0.333785  , -0.05696434, -0.6478315 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [13]:
hpc.train(dataset, logdir='log')

In [17]:
hpc.prediction_error('tier_0')

<tf.Tensor: id=13551, shape=(100, 10), dtype=float32, numpy=
array([[ 5.36607206e-03,  3.21914256e-03,  1.83588266e-03,
        -9.54025984e-03, -6.02674484e-03,  1.52140856e-03,
        -5.58266044e-03, -1.10926181e-02, -4.19443846e-03,
         1.31898224e-02],
       [-1.76793337e-03, -1.24428421e-03, -5.22166491e-04,
        -3.84522974e-03, -6.04540110e-04,  1.92213058e-03,
        -1.67853385e-03, -3.58350947e-03,  5.17249107e-04,
         5.30689955e-03],
       [ 4.40737605e-03,  2.83294916e-03,  6.84261322e-03,
        -1.23717785e-02, -3.19087505e-03,  4.87488508e-03,
        -2.73157656e-03, -7.48910010e-03,  2.56061554e-04,
         7.08171725e-03],
       [-2.13311613e-03,  4.34885034e-04, -1.17338896e-02,
         1.69104338e-02,  1.88544393e-03, -3.97510827e-03,
         3.06952000e-03,  9.37895477e-03,  1.56560540e-03,
        -8.82521272e-03],
       [ 1.29576027e-03,  3.56035307e-03, -6.13734126e-03,
         2.50068307e-03, -4.56848741e-03, -2.97054648e-03,
        -

In [15]:
hpc._raw_tiers

[<tf.Variable 'hierarchical_1_tier_0:0' shape=(None, 10) dtype=float32, numpy=
 array([[ 0.07089106, -0.57464194, -0.42320937,  0.09415009,  0.04514663,
          0.65578663, -0.11440764, -0.20468651,  0.23338884, -0.64779854]],
       dtype=float32)>,
 <tf.Variable 'hierarchical_1_tier_1:0' shape=(None, 4) dtype=float32, numpy=
 array([[ 0.5071081 , -0.30160922,  0.37322018, -0.48421857]],
       dtype=float32)>]